export default {
  //Auth
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  UPDATE_LOGIN: "UPDATE_LOGIN",
  CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",

  //Search Screen
  GET_LIST_SEARCH: "GET_LIST_SEARCH",
  UPDATE_CATEGORY_INDEX: "UPDATE_CATEGORY_INDEX",
  SHOW_ALL_CATEGORY: "SHOW_ALL_CATEGORY",
  PAGE: "PAGE",
  PAGE_PRODUCT: "PAGE_PRODUCT",
  PAGE_POST: "PAGE_POST",
  SEARCH_TEXT: "SEARCH_TEXT",
  IS_MAIN_VIEW_DISPLAY: "IS_MAIN_VIEW_DISPLAY",
  IS_LOADING: "IS_LOADING",
};
